### ISSUE TITLE
As a User I see a different awesome message on my Home screen each day if I restart the app

### ISSUE THREAD

**Issue by proSingularity** [proSingularity/you-are-awesome-app#2]
# Acceptance criteria

- [x] After starting the production app (= installed from GPlay store) on my phone on day 1 I see a specific message for the day (all day long).
- [x] The message for day 1 is the expected one (correct `isoDate`) from the `db.json`
- [x] On the next day, the message changes and I see this message now.
- [x] The message for day 2 is the expected one (correct `isoDate`) from the `db.json`
- [x] If no message for the day is in the db, I see a message randomly chosen from the available ones
- [x] same on a another phone with the prod app installed (in part. I see the same message as on the other phone)
- [x] database contains messages for future 20 days and 2 days in the past 

# Todos

- [x] `db.json` contains posts for next 20 days including 2 past days
- [x] app takes today's post
- [x] app falls back to random post

**Comment by proSingularity** [comment]
https://docs.expo.io/versions/latest/guides/testing-with-jest/

**Comment by proSingularity** [comment]
# Useful tools for json and csv

* https://json-csv.com - paste json, view as spreadsheet
* https://jsonformatter.curiousconcept.com validator and formatter
