### ISSUE TITLE
As a User I want to delete entries from favorites so that I can keep a clear record of my most motivating messages

### ISSUE THREAD

**Issue by proSingularity** [proSingularity/you-are-awesome-app#245]
# Acceptance criteria

- [x] can bulk delete
- [x] dialog asking "Deleted messages will be lost forever. Do you really want to delete?" -> Cancel + Delete button

# DoD

- [x] merged into `master`
- [x] emulator app on `master` still starts
- [x] emulator app on `master` contains the update
- [x] `yarn deploy:prod` succeeded
- [x] production app on my phone still starts
- [x] production app on my phone contains the update
- [x] production app on my phone tests the changed functionality ad-hoc
- [x] merged update to build version to `master`

# Todos 

- [x] long press on specific fav selects pressed fav
- [x] long press enters selection mode (model: Telegram app)
  - [x] every normal press on an unselected fav selects it
  - [x] every normal press on a selected fav unselects it
  - [x] show radio buttons to the left of each fav indicating selected or unselected
  - [x] can exit selection mode via back button on top left
  - [x] can exit selection mode via delete button on top right
    - [x] deletes all selected favs
