### ISSUE TITLE
As a User I see today's awesome message in the notification so that I save time

### ISSUE THREAD

**Issue by proSingularity** [proSingularity/you-are-awesome-app#38]
# Acceptance criteria

- [x] notifications show today's awesome message when cached
- [x] schedule with each days' awesome message as far as possible
- [x] fallback to `"Check out today's awesome greeting. Click to open."`

# Todos

- [x] redux contains all posts with date
- [x] schedule future notifications with the message of the respective day
- [x] schedule fallback
- [ ] (optional) redux store contains minimal representation (remove `currentPost`)
- [ ] (optional) `HomePage` uses selector to allow redux' minimal representation
- [ ] ? future messages are persisted
- [ ] ? messages can be loaded from persistent storage

# DoD

- [x] merged into `master`
- [x] emulator app on `master` still starts
- [x] emulator app on `master` contains the update
- [x] `yarn expo publish` succeeded
- [x] production app on my phone still starts
- [x] production app on my phone contains the update
- [x] production app on my phone tests the changed functionality ad-hoc
