### ISSUE TITLE
As an Admin I want to ensure that there is at most one cronjob for a specific push token

### ISSUE THREAD

**Issue by proSingularity** [proSingularity/you-are-awesome-app#94]
so that users do not receive multiple messages on a given day, and I do not have any maintenance work from fixing that. 

# Acceptance criteria

- [x] ensured that there is at most one cronjob for a specific push token

# Todos

- [ x `register` lambda function should check for existence
- [x] `edit` the cronjob if already existent to update time
- [x] `add` a cronjob if none exists for the given token
- [ ] ~~consider removal of button freeze in settings page~~ --> still makes sense to give the BE some time and avoid multiple clicks in short time frame.   

# DoD

- [ ] merged into `master`
- [ ] emulator app on `master` still starts
- [ ] emulator app on `master` contains the update
- [ ] `yarn expo publish` succeeded
- [ ] production app on my phone still starts
- [ ] production app on my phone contains the update
- [ ] production app on my phone tests the changed functionality ad-hoc
